language: python
python:
  - '3.6.7'
install: 
  - pip install -r requirements.txt
  - pip install coveralls
 
 services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE stack;" -U postgres

script: 
  - pytest 
  
after_success:
  - coveralls
  
  
cache: pip
